### ISSUE TITLE
how to import crossbeam-skiplist

### ISSUE THREAD

**Issue by M1123581E** [crossbeam-rs/crossbeam#562]
i want to use  crossbeam-skiplist but it is not included in crossbeam. so what i should to add in Cargo.toml

**Comment by taiki-e** [comment]
As skiplist hasn't been released yet, you have to use [git dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) to use it, like:
```toml
[dependencies.crossbeam-skiplist]
git = "https://github.com/crossbeam-rs/crossbeam.git"
tag = "crossbeam-0.7.3"
```
